# Generated by Django 3.2 on 2025-02-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=28, primary_key=True, serialize=False),
        ),
    ]
