# Generated by Django 3.2 on 2025-02-12 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0002_auto_20250212_1810'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HostelApproval',
            new_name='HostelApprovalEdit',
        ),
        migrations.RenameField(
            model_name='hostelapprovaledit',
            old_name='current_status',
            new_name='status',
        ),
    ]
