# Generated by Django 3.2 on 2025-02-12 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0003_auto_20250212_1813'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HostelApprovalEdit',
            new_name='HostelApproval',
        ),
    ]
