# Generated by Django 3.2 on 2025-02-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0004_rename_hostelapprovaledit_hostelapproval'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='hostel_type',
            field=models.CharField(blank=True, choices=[('boys', 'Boys'), ('girls', 'Girls')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='food',
            field=models.ManyToManyField(to='rental_app.Food'),
        ),
    ]
