# Generated by Django 3.2 on 2025-02-16 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0007_auto_20250215_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='role',
        ),
    ]
