# Generated by Django 3.2 on 2025-02-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0009_alter_payment_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.TextField(editable=False, unique=True),
        ),
    ]
