# Generated by Django 3.2 on 2025-02-16 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0012_alter_payment_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='read_status',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
