# Generated by Django 3.2 on 2025-02-16 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0013_alter_notification_read_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='role',
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='apartment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rental_app.apartment'),
        ),
    ]
