# Generated by Django 3.2 on 2025-02-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0014_auto_20250217_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='admin',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
    ]
