# Generated by Django 3.2 on 2025-02-17 19:06

from django.db import migrations, models
import rental_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0017_auto_20250217_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='checkout_data',
            field=models.DateTimeField(default=rental_app.models.default_checkout_date),
        ),
    ]
