# Generated by Django 3.2 on 2025-02-19 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0019_auto_20250219_0713'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
