# Generated by Django 3.2 on 2025-02-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0020_delete_emailverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
