# Generated by Django 3.2 on 2025-02-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0021_otpverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseowner',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
