# Generated by Django 3.2 on 2025-04-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0025_auto_20250223_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
