# Generated by Django 3.2 on 2025-04-06 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0026_chat_is_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-timestamp']},
        ),
    ]
