# Generated by Django 3.2 on 2025-04-08 06:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0028_auto_20250408_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='wishlist_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
