# Generated by Django 3.2 on 2025-04-08 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0030_auto_20250408_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_app.apartment'),
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'apartment')},
        ),
    ]
