# Generated by Django 3.2 on 2025-04-08 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0031_auto_20250408_0646'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set(),
        ),
    ]
