# Generated by Django 3.2 on 2025-04-08 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0032_alter_wishlist_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='apartment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rental_app.apartment'),
        ),
    ]
